function lambda = A_eigenvalues(a,x)
%A_EIGENVALUES
%    LAMBDA = A_EIGENVALUES(A,X)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    18-Jul-2023 19:20:20

t2 = x.^2;
t3 = x.*(1.0./2.0);
t4 = a.^2;
t5 = t4.*4.0;
t6 = t2.*-2.0+t5+x+t2.*x;
t7 = t6.*x;
t8 = sqrt(t7);
t9 = t2.*(1.0./2.0);
lambda = [t3-t8.*(1.0./2.0)+t9;t3+t8.*(1.0./2.0)+t9];
