function V = A_eigenvectors(a,x)
%A_EIGENVECTORS
%    V = A_EIGENVECTORS(A,X)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    18-Jul-2023 19:20:21

t2 = 1.0./a;
t3 = x.^2;
t4 = 1.0./x;
t5 = x.*(1.0./2.0);
t6 = a.^2;
t7 = t6.*4.0;
t8 = t3.*-2.0+t7+x+t3.*x;
t9 = t8.*x;
t10 = sqrt(t9);
t11 = t3.*(1.0./2.0);
V = reshape([-t2.*x+t2.*t4.*(t5-t10.*(1.0./2.0)+t11),1.0,-t2.*x+t2.*t4.*(t5+t10.*(1.0./2.0)+t11),1.0],[2, 2]);
