% A unit sphere centered at the origin and
% generated by three matrices x, y, and
% z of size 21 * 21 each.

%sphere(20)
%axis('square')
%OR

[x,y,z] = sphere(20)
surf(x,y,z)
%axis('equal')
axis('square')